### ISSUE TITLE
搜索功能是不是有问题

### ISSUE THREAD

**Issue by GitCourser** [taoran1401/tools-web#3]
演示站 [https://tools.ranblogs.com/](https://tools.ranblogs.com/) 上方的搜索框什么都搜不出来
下面第一个功能就是"随机密码生成", 结果搜索"密码"都没反应

**Comment by taoran1401** [comment]
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/1c697edc-0d8b-4a76-9666-8e502dcb645d">

试了一下，能搜索

**Comment by naroat** [comment]
谢谢你的反馈，已发现问题，多次搜索后确实会出现没搜索到数据问题，明天会发布一个修复版本
