### ISSUE TITLE
如何使用自定义路径访问？

### ISSUE THREAD

**Issue by fuyun8774** [taoran1401/tools-web#4]
npm install pnpm -g
pnpm build

打包之后只能通过跟路径访问，想通过自定义后缀转发要怎么配？

https://tools.ranblogs.com/

**Comment by taoran1401** [comment]
你这后缀是二级目录的意思吧，tools-web没有一键配置，但是可以通过下面几个步骤来完成：
- 修改router访问路径，`./src/router/index.ts`中`createWebHistory`传递参数一个基础路径，这一步可以让项目在二级目录下正确的找到路由，如下：
![image](https://github.com/user-attachments/assets/0caa0651-85a6-41f4-8198-589a32be8c38)

- build添加基础路径配置, `./package.json`文件修改，这一步可以使打包项目时包含二级目录，如下：
![image](https://github.com/user-attachments/assets/9ae7bba6-c669-4703-b3ce-8ed8881263a1)

- nginx配置
```
location /tools {
	alias /home/www/tools-web/dist;
        index index.html index.htm;
        try_files  $uri $uri/ /tools/index.html @rewrites; 
}
```
