### ISSUE TITLE
ssr未生效

### ISSUE THREAD

**Issue by wangchenyang** [taoran1401/tools-web#6]
拉取了pro/full分支，各种基础操作执行完毕，启动后如何实现ssr效果，执行pnpm build:dev打包命令，部署后ssr效果仍未实现，请问还需要做其他操作吗
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/ba6c0f8e-1c1e-4d16-8728-d808f859b929">

**Comment by naroat** [comment]
不用拉取pro/full分支，功能全在master分支上，使用`pnpm build:pro`会根据`.env.production`配置文件生成静态页面，如果没有`.env.production`文件，可以将`.env.development`复制一份出来并将里面的`NODE_ENV`的值改为`production`

**Comment by wangchenyang** [comment]
明白了，感谢！
